### ISSUE TITLE
DB setup

### ISSUE THREAD

**Issue by clemcodes** [Walk2Zero/walk2zero#5]
# Original tasks
- [x] design DB and tables (aim for 3NF) – can display as an ER diagram
- [x] write SQL script that creates the DB
- [x] write stored programs (e.g. triggers) for any calculations and auto populations that are required
- [x] research average carbon emissions per km for each vehicle type and populate the vehicles table with this data, also decide on final vehicle selection for prototype
- [x] add a couple of sample users to run some queries in MySQL to test the DB

---

# Extra tasks assigned to Robyn (2021-08-10)
- [x] add emissions saved column to emissions table
- [x] update vehicles table with CO2/km data from a single source (UK gov stats)
- [x] remove vehicles we won't be using (e.g. train) from the vehicles table

**Comment by robynfsj** [comment]
Extra tasks assigned to me
---------------------------
- [ ] add emissions saved column to emissions table
- [ ] update vehicles table with CO2/km data from a single source (UK gov stats)
- [ ] remove vehicles we won't be using (e.g. train) from the vehicles table
